version: '3.6'

services:

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "80:5433"
    environment:
      PGADMIN_DEFAULT_EMAIL: container@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: Conta1ner
      PGADMIN_SERVER_NAME: pgadmin4
    links:
      - postgres

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: changeit
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    links:
      - zookeeper
      - kafka

